[gcp_service_account]
type = "service_account"
project_id = "tracker-app-463507"
private_key_id = "7e9a14c4214ea767dcabf7908af346173bc9478d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCuMiJ57EDyseH8
crX6XZ8/YkELERGyhhjMV/pxfwXKlXVjtqdEcrPlrjUr2AOSqz8GeJV2rakhFBdb
HViyN+8JPfV4tGepKfpl1cJeS+EfaTQkhP3JOj6oAg5mkiaq/xTmGV1a/HkvG/GG
s/MSl5KMJ2O8dfVZgdhEdKHxVbPwJD6w0lSWjJsQiZxE1bWt1v3H3ATmmqKk4OWS
Au8qRqEhSfJEsQ/isH1VmahI43cX04sh0U0ZgAK/+R+cXRj1i92bDqD9RWwAYKGg
1COReaFdXiVye+KgIf4f0LdT/er+pdGOh/6g9pwqURsgZEpYq2iY8f4xrkUdKi5r
SCqXkdcvAgMBAAECggEAAP6EcmXWof/tP+/dyYIHDMsvWw0SqlyOUrxvmV/hL4X9
iTlbg3bHnOs/qq0fswOpIGdFAfxHMGqsBXo2yiKA3J2/cVDZ2qg1hm3PMYEIPEyl
3O1U6zi+/KM/BoxBNVOCP+XDzHNU3gPxAGqdnhKDNIddZpLVfuAJyPdp0wo073Ub
jeNWow7N7gqTSBCgLxNsNZp82h84n9mMQrMitSb4SD+pitclWDCRozo46bAAlDtR
C3f5Orjr4bdhvFtrUL9+orFPdzG8UzcRzZkJLJSdB7VN9qdBqRNVJDEuUA5LG125
XSUZi0ixQ87JMeeYTlpWgZr3gxS2FJ1im9tU5PJmsQKBgQDjSGACspSiLaaFEjTr
oSwOPKjNBZvJ8xrnQn6gZAsBaJyEEY91G+j+LY0P132SoEKOuk9Wa5yvf/+X4r3a
P/2GhmArt3MwYncoddOfBWj1c5n7cLt8J/guM8AZwOOswu1/p+PUDrPmRnVDankL
Sl5va/Y0XiIAID+xDpxd7o9yjQKBgQDENKA+FebnF7c0X8xGp5B7w77+CTRdCsoO
eGHt7FRX94UOgYD5CPnwV/T0ttrZHWiwxofpRY/VPK2nf8raNFlxXNSpEi0IQXTc
uyrn3QTLvUSrq5Ex691pswO1iz9vlR9ZzxYcfeN7+iTIRxWVZCCVVvCe5L0fSJUX
hqE0WrZfqwKBgQCmle6hK4kbkYAiuuSE7D3hNX63vuufyoqmhCtRneIfJzDI8CII
wOs2GebxfI1ygfomqNHr0rYmQBfzmGJ07EADcMxeXniUNyeFRU9Vl96FQTTUgZ05
dAZIvu+HMMTvZHQ1A7ZOQHSFTJE4V3re1qR+4E+1tGURWJG2UbI0et0zJQKBgQCy
mt1L5xAcSYBiUtpXbu2dXGEeSy65i7rHVVqABOP6d71NqSHIkR1EZiz8HwA1KApG
8VKDTOlTyTqjATedTo4lHcYQahVIMJ262T6DdrSI6q/6PeGcOgOB1o2H00xZvLuf
O137bbWJA/o7vkmthkoK5+t+GOb39VCS6+EPEYx2pQKBgFDaf0CzAv3+ymTx5vlV
gdahiWf2Io8wXZWBMdhLb+n5f5ZRVBh+QWdT2vDKPykjZ3vKFa+xrNF53qjPAHjL
L03begzuZu/5u4eB/UdPf9D8PZ5AJLfIn4+feJ+jmbUFG81dj37m9hKBzTwfXd9F
L7GHdCsW3a3yuFYuThJ2itnW
-----END PRIVATE KEY-----"""
client_email = "sheets-bot@tracker-app-463507.iam.gserviceaccount.com"
client_id = "113646466167039771708"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheets-bot%40tracker-app-463507.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

sheet_name = "TrackerDB"
